[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = ["npm ci --production=false"]

[phases.build]
cmds = [
  "cd frontend && npm ci && npm run build && cd ..",
  "cd backend && npm ci && npm run build && cd .."
]

[start]
cmd = "cd backend && npm start"

[variables]
NODE_ENV = "production"